services:
  wasap:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data
      - whisper_cache:/home/appuser/.cache/huggingface
    depends_on:
      - ollama
    network_mode: host
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11435
    network_mode: host
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok
    command: http --url=${NGROK_DOMAIN} --log=stdout http://localhost:8000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    network_mode: host
    depends_on:
      - wasap
    restart: unless-stopped

volumes:
  ollama_data:
  whisper_cache:
